# Generated by Django 4.2.8 on 2024-01-04 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_countminsketch_delete_edits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countminsketch',
            old_name='data',
            new_name='serialized_data',
        ),
    ]
