# Generated by Django 4.2.8 on 2024-01-05 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0003_rename_data_countminsketch_serialized_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CountMinSketch',
            new_name='CountMinSketchModel',
        ),
    ]
