# Generated by Django 4.2.8 on 2024-01-05 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0004_rename_countminsketch_countminsketchmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountMinSketchKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keys', models.TextField()),
                ('count_min_sketch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logger.countminsketchmodel')),
            ],
        ),
    ]
